name: Veracode-Fix in GitHub
on:
  workflow_dispatch:
    inputs:
      secondaryupload:
        type: boolean
        required: true
        description: "Run secondary upload of Sarif (test)"
        default: false
        
  
env:
  SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}

permissions:
  actions: read
  #attestations: write
  checks: write
  contents: write
  #deployments: read|write|none
  #id-token: write|none
  issues: write
  #models: read|none
  #discussions: read|write|none
  packages: write
  #pages: read|write|none
  pull-requests: write
  security-events: write
  statuses: write
jobs:
  build:
    runs-on: ubuntu-latest
    # grants permissions for the artifact to be uploaded
 
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acces it and clones the repo
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          
      - name: Build with Maven
        run: |
          mvn -B clean package --file app/pom.xml
          ls -la app/target/verademo.war
          chmod +rx app/target/verademo.war
          ls -la app/target/verademo.war
          
      - uses: actions/upload-artifact@v4
        with:
          name: verademo.war
          path: app/target/verademo.war
            
  pipeline_scan:
      needs: build
      runs-on: ubuntu-latest
      name: veracode pipeline scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v3
    
        - name: get archive
          uses: actions/download-artifact@v4
          with:
            name: verademo.war
        
        - name: pipeline-scan action step
          id: pipelien-scan
          uses: veracode/Veracode-pipeline-scan-action@esd-true
          with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            file: "verademo.war" 
            request_policy: "Veracode Recommended SCA Very Low"
            debug: 1
            fail_build: false

        - run: |
            ls 
            pwd
            
    #    - uses: actions/upload-artifact@v4
    #      with:
    #        name: Veracode Pipeline-Scan Results
    #        path: results.json 
            
        - uses: actions/upload-artifact@v4
          with:
            name: Veracode Pipeline-Scan Filtered Results
            path: filtered_results.json 

        - name: Veracode Static Analysis Pipeline Scan and SARIF import
          # You may pin to the exact commit or the version.
          # uses: veracode/veracode-pipeline-scan-results-to-sarif@bbb92f8ccedc6c38e07d32c16cf2f690e7b4ba08
          uses: veracode/veracode-pipeline-scan-results-to-sarif@v2.0.4
          with:
            scan-type: pipeline
            #results-json: results.json
            pipeline-results-json: results.json
            output-results-sarif: veracode-results.sarif
            source_base_path_1: "com/:app/src/main/java/com/"
            source_base_path_2: "WEB-INF:app/src/main/webapp/WEB-INF"
            #source-base-path-3: # optional, default is 
            finding-rule-level: 4:3:0 # default is 4:3:0
            repo_owner:  ${{ github.repository.owner }} # optional
            repo_name: ${{ github.repository.name }} # optional
            githubToken: ${{ github.token }} # default is ${{ github.token }}
            ref: ${{ github.ref }} # default is ${{ github.ref }}
            commitSHA: ${{ github.sha }} # default is ${{ github.sha }}
            #noupload: # optional, default is false
                  
        - name: Upload SARIF file
          if: ${{ inputs.secondaryupload }}
          uses: github/codeql-action/upload-sarif@v3
          with:
            # Path to SARIF file relative to the root of the repository
            sarif_file: veracode-results.sarif
            # Optional category for the results
            # Used to differentiate multiple results for one commit
            category: Veracode Static Analysis

  veracode-fix:
      runs-on: ubuntu-latest
      needs: pipeline_scan
      name: veracode fix
      steps:
        - name: checkout repo
          uses: actions/checkout@v3
  
        - name: get flaw file
          uses: actions/download-artifact@v4
          with:
            name: Veracode Pipeline-Scan Results
            
        - name: Create fixes from static findings
          id: convert
          uses: Veracode/veracode-fix@v1.0.3 #   uses: Veracode/veracode-fix@main
          with:
            inputFile: results.json
            #fixType: batch
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            source-base-path-1: "com/:app/src/main/java/com/"
            source-base-path-2: "WEB-INF:app/src/main/webapp/WEB-INF"
            language: java
            createPR: true
            #prComment: true
            #debug: true
            cwe: '117'
            fixType: single
            files: all
            debug: true
            prComment: true
            codeSuggestion: true
